name: Update Recent Activity

on:
  schedule:
    - cron: "*/30 * * * *"  # 每30分钟更新
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Activity
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: Readme-Workflows/recent-activity@2.330.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update Recent Activity"
          MAX_LINES: 5
